version: '3.3'
services:
    app:
        user: "1000"
        build:
            context: ./
            dockerfile: ./Dockerfile
        working_dir: /home/workspace/programming-typescript
        volumes:
            - ./:/home/workspace/programming-typescript
        tty:
            true
